import { ProductInfo } from "../core";

export const Data: ProductInfo[] = [
  {
    id: 1,
    picUrl: "./assets/woman_1.jpg",
    title: "Top",
    selected: false,
    price: 30,
    type: "woman",
  },
  {
    id: 2,
    picUrl: "./assets/woman_2.jpg",
    title: "Long-sleeve",
    selected: false,
    price: 45,
    type: "woman",
  },
  {
    id: 3,
    picUrl: "./assets/woman_3.jpg",
    title: "Shirt Woman",
    selected: false,
    price: 45,
    type: "woman",
  },
  {
    id: 4,
    picUrl: "./assets/woman_4.jpg",
    title: "Dress",
    selected: false,
    price: 190,
    type: "woman",
  },
  {
    id: 5,
    picUrl: "./assets/woman_5.jpg",
    title: "White Dress",
    selected: false,
    price: 220,
    type: "woman",
  },
  {
    id: 6,
    picUrl: "./assets/woman_6.jpg",
    title: "Pink Trousers",
    selected: false,
    price: 60,
    type: "woman",
  },
  {
    id: 7,
    picUrl: "./assets/woman_7.jpg",
    title: "Casual Set",
    selected: false,
    price: 110,
    type: "woman",
  },
  {
    id: 8,
    picUrl: "./assets/woman_8.jpg",
    title: "Spring Dress",
    selected: false,
    price: 80,
    type: "woman",
  },
  {
    id: 9,
    picUrl: "./assets/man_1.jpg",
    title: "Polo Shirt",
    selected: false,
    price: 50,
    type: "man",
  },
  {
    id: 10,
    picUrl: "./assets/man_2.jpg",
    title: "T-shirt White",
    selected: false,
    price: 40,
    type: "man",
  },
  {
    id: 11,
    picUrl: "./assets/man_3.jpg",
    title: "Trousers Man",
    selected: false,
    price: 70,
    type: "man",
  },
  {
    id: 12,
    picUrl: "./assets/man_4.jpg",
    title: "T-shirt Man",
    selected: false,
    price: 35,
    type: "man",
  },
  {
    id: 13,
    picUrl: "./assets/man_5.jpg",
    title: "Set Shirts",
    selected: false,
    price: 80,
    type: "man",
  },
  {
    id: 14,
    picUrl: "./assets/man_6.jpg",
    title: "Shirt Man",
    selected: false,
    price: 90,
    type: "man",
  },
  {
    id: 15,
    picUrl: "./assets/man_7.jpg",
    title: "Autumn Set",
    selected: false,
    price: 205,
    type: "man",
  },
  {
    id: 16,
    picUrl: "./assets/man_8.jpg",
    title: "Young Set",
    selected: false,
    price: 160,
    type: "man",
  },
];