import { ProductInfo } from "../core";

export const Data: ProductInfo[] = [
  {
    id: 1,
    picUrl: "./assets/woman_1.jpg",
    title: "Shirt woman",
    selected: false,
    price: 40,
    type: "woman",
  },
  {
    id: 2,
    picUrl: "./assets/woman_2.jpg",
    title: "T-shirt woman",
    selected: false,
    price: 40,
    type: "woman",
  },
  {
    id: 3,
    picUrl: "./assets/woman_3.jpg",
    title: "T-shirt woman",
    selected: false,
    price: 45,
    type: "woman",
  },
  {
    id: 4,
    picUrl: "./assets/woman_4.jpg",
    title: "Shirt",
    selected: false,
    price: 90,
    type: "woman",
  },
  {
    id: 5,
    picUrl: "./assets/woman_5.jpg",
    title: "Jacket",
    selected: false,
    price: 100,
    type: "woman",
  },
  {
    id: 6,
    picUrl: "./assets/woman_6.jpg",
    title: "Shirt woman",
    selected: false,
    price: 90,
    type: "woman",
  },
  {
    id: 7,
    picUrl: "./assets/woman_7.jpg",
    title: "Shirt woman spring",
    selected: false,
    price: 90,
    type: "woman",
  },
  {
    id: 8,
    picUrl: "./assets/woman_8.jpg",
    title: "Dress",
    selected: false,
    price: 150,
    type: "woman",
  },
  {
    id: 9,
    picUrl: "./assets/man_1.jpg",
    title: "T-shirt man",
    selected: false,
    price: 50,
    type: "man",
  },
  {
    id: 10,
    picUrl: "./assets/man_2.jpg",
    title: "T-shirt man",
    selected: false,
    price: 50,
    type: "man",
  },
  {
    id: 11,
    picUrl: "./assets/man_3.jpg",
    title: "Set Shirts",
    selected: false,
    price: 130,
    type: "man",
  },
  {
    id: 12,
    picUrl: "./assets/man_4.jpg",
    title: "Article man colorful",
    selected: false,
    price: 60,
    type: "man",
  },
  {
    id: 13,
    picUrl: "./assets/man_5.jpg",
    title: "Shirt",
    selected: false,
    price: 80,
    type: "man",
  },
  {
    id: 14,
    picUrl: "./assets/man_6.jpg",
    title: "Shoes",
    selected: false,
    price: 150,
    type: "man",
  },
  {
    id: 15,
    picUrl: "./assets/man_7.jpg",
    title: "Flip flop",
    selected: false,
    price: 25,
    type: "man",
  },
  {
    id: 16,
    picUrl: "./assets/man_8.jpg",
    title: "Trousers",
    selected: false,
    price: 100,
    type: "man",
  },
];