import { ProductInfo } from "../core";

export const Data: ProductInfo[] = [
  {
    id: 1,
    picUrl: "./assets/ropa6.jpg",
    title: "Shirt woman",
    selected: false,
    price: 40,
    type: "woman",
  },
  {
    id: 2,
    picUrl: "./assets/ropa18.jpg",
    title: "T-shirt woman",
    selected: false,
    price: 40,
    type: "woman",
  },
  {
    id: 3,
    picUrl: "./assets/ropa10.jpg",
    title: "T-shirt woman",
    selected: false,
    price: 45,
    type: "woman",
  },
  {
    id: 4,
    picUrl: "./assets/ropa17.jpg",
    title: "Shirt",
    selected: false,
    price: 90,
    type: "woman",
  },
  {
    id: 5,
    picUrl: "./assets/ropa5.jpg",
    title: "Jacket",
    selected: false,
    price: 100,
    type: "woman",
  },
  {
    id: 6,
    picUrl: "./assets/ropa20.jpg",
    title: "Shirt woman",
    selected: false,
    price: 90,
    type: "woman",
  },
  {
    id: 7,
    picUrl: "./assets/ropa22.jpg",
    title: "Shirt woman spring",
    selected: false,
    price: 90,
    type: "woman",
  },
  {
    id: 8,
    picUrl: "./assets/ropa19.jpg",
    title: "Dress",
    selected: false,
    price: 150,
    type: "woman",
  },
  {
    id: 9,
    picUrl: "./assets/ropa7.jpg",
    title: "T-shirt man",
    selected: false,
    price: 50,
    type: "man",
  },
  {
    id: 10,
    picUrl: "./assets/ropa25.jpg",
    title: "T-shirt man",
    selected: false,
    price: 50,
    type: "man",
  },
  {
    id: 11,
    picUrl: "./assets/ropa8.jpg",
    title: "Set Shirts",
    selected: false,
    price: 130,
    type: "man",
  },
  {
    id: 12,
    picUrl: "./assets/ropa9.jpg",
    title: "Article man colorful",
    selected: false,
    price: 60,
    type: "man",
  },
  {
    id: 13,
    picUrl: "./assets/ropa11.jpg",
    title: "Shirt",
    selected: false,
    price: 80,
    type: "man",
  },
  {
    id: 14,
    picUrl: "./assets/shoes2.jpg",
    title: "Shoes",
    selected: false,
    price: 150,
    type: "man",
  },
  {
    id: 15,
    picUrl: "./assets/flipflop.jpg",
    title: "Flip flop",
    selected: false,
    price: 25,
    type: "man",
  },
  {
    id: 16,
    picUrl: "./assets/ropa12.jpg",
    title: "Trousers",
    selected: false,
    price: 100,
    type: "man",
  },
];